"""Add follow-up message fields to campaigns

Revision ID: 1549afa921ca
Revises: 2ead0df99249
Create Date: 2025-09-03 17:21:10.367263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1549afa921ca'
down_revision: Union[str, None] = '2ead0df99249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns_new', sa.Column('follow_up_message_1', sa.Text(), nullable=True))
    op.add_column('campaigns_new', sa.Column('follow_up_delay_1', sa.Integer(), nullable=True))
    op.add_column('campaigns_new', sa.Column('follow_up_message_2', sa.Text(), nullable=True))
    op.add_column('campaigns_new', sa.Column('follow_up_delay_2', sa.Integer(), nullable=True))
    op.add_column('campaigns_new', sa.Column('follow_up_message_3', sa.Text(), nullable=True))
    op.add_column('campaigns_new', sa.Column('follow_up_delay_3', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns_new', 'follow_up_delay_3')
    op.drop_column('campaigns_new', 'follow_up_message_3')
    op.drop_column('campaigns_new', 'follow_up_delay_2')
    op.drop_column('campaigns_new', 'follow_up_message_2')
    op.drop_column('campaigns_new', 'follow_up_delay_1')
    op.drop_column('campaigns_new', 'follow_up_message_1')
    # ### end Alembic commands ###
