"""Add more DuxSoup fields to contacts

Revision ID: 2ead0df99249
Revises: f215131b486f
Create Date: 2025-09-02 21:25:22.323833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ead0df99249'
down_revision: Union[str, None] = 'f215131b486f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('recruiter_profile_url', sa.String(length=500), nullable=True))
    op.add_column('contacts', sa.Column('company_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'company_id')
    op.drop_column('contacts', 'recruiter_profile_url')
    # ### end Alembic commands ###
