"""Add data source tracking fields to contacts

Revision ID: 78b79476732f
Revises: c8cfa159a3f0
Create Date: 2025-09-02 20:22:42.560809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78b79476732f'
down_revision: Union[str, None] = 'c8cfa159a3f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('data_source', sa.String(length=50), nullable=True))
    op.add_column('contacts', sa.Column('source_id', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('import_batch_id', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('data_quality_score', sa.Integer(), nullable=True))
    op.add_column('contacts', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('contacts', sa.Column('job_title', sa.String(length=255), nullable=True))
    op.add_column('contacts', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.add_column('contacts', sa.Column('company_size', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('company_website', sa.String(length=500), nullable=True))
    op.add_column('contacts', sa.Column('connection_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'connection_count')
    op.drop_column('contacts', 'company_website')
    op.drop_column('contacts', 'company_size')
    op.drop_column('contacts', 'company_name')
    op.drop_column('contacts', 'job_title')
    op.drop_column('contacts', 'full_name')
    op.drop_column('contacts', 'data_quality_score')
    op.drop_column('contacts', 'import_batch_id')
    op.drop_column('contacts', 'source_id')
    op.drop_column('contacts', 'data_source')
    # ### end Alembic commands ###
