"""Add assigned_to field to campaign_contacts

Revision ID: 94decf0cecde
Revises: 78b79476732f
Create Date: 2025-09-02 20:57:24.827954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94decf0cecde'
down_revision: Union[str, None] = '78b79476732f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_contacts') as batch_op:
        batch_op.add_column(sa.Column('assigned_to', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_campaign_contacts_assigned_to', 'user', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_contacts') as batch_op:
        batch_op.drop_constraint('fk_campaign_contacts_assigned_to', type_='foreignkey')
        batch_op.drop_column('assigned_to')
    # ### end Alembic commands ###
