"""Add DuxSoup workflow fields to campaigns

Revision ID: c8cfa159a3f0
Revises: febdbc88f63d
Create Date: 2025-09-02 20:03:25.562973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8cfa159a3f0'
down_revision: Union[str, None] = 'febdbc88f63d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first (SQLite limitation)
    op.add_column('campaigns_new', sa.Column('initial_action', sa.String(length=50), nullable=True))
    op.add_column('campaigns_new', sa.Column('initial_message', sa.Text(), nullable=True))
    op.add_column('campaigns_new', sa.Column('initial_subject', sa.String(length=255), nullable=True))
    op.add_column('campaigns_new', sa.Column('follow_up_actions', sa.JSON(), nullable=True))
    op.add_column('campaigns_new', sa.Column('delay_days', sa.Integer(), nullable=True))
    op.add_column('campaigns_new', sa.Column('random_delay', sa.Boolean(), nullable=True))
    
    # Update existing rows with default values
    op.execute("UPDATE campaigns_new SET initial_action = 'inmail' WHERE initial_action IS NULL")
    op.execute("UPDATE campaigns_new SET delay_days = 1 WHERE delay_days IS NULL")
    op.execute("UPDATE campaigns_new SET random_delay = 1 WHERE random_delay IS NULL")
    
    # Now make the required columns NOT NULL (SQLite doesn't support this directly, so we'll keep them nullable)
    # The application layer will handle the validation
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns_new', 'random_delay')
    op.drop_column('campaigns_new', 'delay_days')
    op.drop_column('campaigns_new', 'follow_up_actions')
    op.drop_column('campaigns_new', 'initial_subject')
    op.drop_column('campaigns_new', 'initial_message')
    op.drop_column('campaigns_new', 'initial_action')
    # ### end Alembic commands ###
