"""Add DuxSoup fields to contacts

Revision ID: f215131b486f
Revises: 94decf0cecde
Create Date: 2025-09-02 21:18:50.540325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f215131b486f'
down_revision: Union[str, None] = '94decf0cecde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('scan_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('contacts', sa.Column('sales_profile_url', sa.String(length=500), nullable=True))
    op.add_column('contacts', sa.Column('public_profile_url', sa.String(length=500), nullable=True))
    op.add_column('contacts', sa.Column('middle_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'middle_name')
    op.drop_column('contacts', 'public_profile_url')
    op.drop_column('contacts', 'sales_profile_url')
    op.drop_column('contacts', 'scan_time')
    # ### end Alembic commands ###
