"""Add follow-up action fields to campaigns

Revision ID: f772e0c9879c
Revises: 1549afa921ca
Create Date: 2025-09-03 17:29:56.392164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f772e0c9879c'
down_revision: Union[str, None] = '1549afa921ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns_new', sa.Column('follow_up_action_1', sa.String(length=50), nullable=True))
    op.add_column('campaigns_new', sa.Column('follow_up_subject_1', sa.String(length=255), nullable=True))
    op.add_column('campaigns_new', sa.Column('follow_up_action_2', sa.String(length=50), nullable=True))
    op.add_column('campaigns_new', sa.Column('follow_up_subject_2', sa.String(length=255), nullable=True))
    op.add_column('campaigns_new', sa.Column('follow_up_action_3', sa.String(length=50), nullable=True))
    op.add_column('campaigns_new', sa.Column('follow_up_subject_3', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns_new', 'follow_up_subject_3')
    op.drop_column('campaigns_new', 'follow_up_action_3')
    op.drop_column('campaigns_new', 'follow_up_subject_2')
    op.drop_column('campaigns_new', 'follow_up_action_2')
    op.drop_column('campaigns_new', 'follow_up_subject_1')
    op.drop_column('campaigns_new', 'follow_up_action_1')
    # ### end Alembic commands ###
